<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Learning\DotNet\Develop\API\GlobalExceptionHandling\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Learning\DotNet\Develop\API\GlobalExceptionHandling\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>

</Project>
